<?php
$this->title = "Delete player";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete number 
'<?php echo $this->escape($this->hockey['number']); ?>' 
'<?php echo $this->escape($this->hockey['name']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->hockey['id']; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>
